#Daniel Mogil
print("Grace Hopper was a computer science pioneer who invented one of the first linkers.")
print("A linker combines multiple object files into a single executable.")
print("Hopper coined the phrase \"bug\" when a moth caused problems in her early computer.")

x = input("Have you heard of Grace Hopper? ")
print("She is pretty cool, isn't she.")

print("   /\\  ")
print("  /  \\  ")
print(" /    \\")
print("/ .  . \\")
print("\      /")
print(" \ -- /")
print("  \  /")
print("   \/")
print(" \ || /")
print("  \||/")
print("   ||")
print("   ||")
print("  /  \\")
print(" /    \\")
